on:
  workflow_run:
    workflows: ['Standard Jobs']
    branches: [master]
    types:
      - completed

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy step
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            (mkdir "${{ secrets.PROJ_PATH }}" || true)
            cd "${{ secrets.PROJ_PATH }}"
            (git pull origin master || git clone git@github.com:War-Against-Covid/waragainstcovid-backend.git .)
            echo -e "${{secrets.ENV}}" > .env
            just run-prod