on:
  workflow_run:
    workflows: ['Standard Jobs']
    branches: [master]
    types:
      - completed

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy step
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/waragainstcovid/waragainstcovid-website
            git pull
            just pull-backend
            echo -e "${{secrets.ENV}}" > ./waragainstcovid-backend/.env
            just build-prod
            npx pm2 kill
            npx pm2 start