on: [push]

name: Standard Jobs

jobs:
  run-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Setup dependencies
        run: yarn install
      - name: Run lints
        run: yarn lint